[project]
name = "NEAT_Playground"
version = "0.0.1"
authors = [
  { name="Tom Draper", email="mythirdalias@gmail.com" },
]
description = "A small place for me to expand learning NEAT and other cool python things."
readme = "README.md"

[project.urls]
Homepage = "https://github.com/TomDraper/NEAT_Playground"
Portfolio = "https://tomdraper.github.io/Profile/"

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"